# Import libraries

In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder
# conda install -c conda-forge mlxtend

In [5]:
movie = pd.read_csv("C:\\Users\\sathya\\Documents\\datascience\\Movie (1).csv")
movie.head()

   userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [6]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8992 entries, 0 to 8991
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   userId  8992 non-null   int64
 1   movie   8992 non-null   object
 2   rating  8992 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 210.9+ KB

In [7]:
movie.shape

(8992, 3)

In [8]:
movie.isnull().sum()

userId    0
movie     0
rating    0
dtype: int64

# Pre-Processing
As the data is not in transaction formation 
We are using transaction Encoder

In [13]:
df=pd.get_dummies(movie)
df.head(20)

,userId,rating,movie_Father of the Bride Part II (1995),movie_GoldenEye (1995),movie_Grumpier Old Men (1995),movie_Heat (1995),movie_Jumanji (1995),movie_Sabrina (1995),movie_Sudden Death (1995),movie_Tom and Huck (1995),movie_Toy Story (1995),movie_Waiting to Exhale (1995)
0,3,4.0,0,0,0,0,0,0,0,0,1,0
1,6,5.0,0,0,0,0,0,0,0,0,1,0
2,8,4.0,0,0,0,0,0,0,0,0,1,0
3,10,4.0,0,0,0,0,0,0,0,0,1,0
4,11,4.5,0,0,0,0,0,0,0,0,1,0
5,12,4.0,0,0,0,0,0,0,0,0,1,0
6,13,4.0,0,0,0,0,0,0,0,0,1,0
7,14,4.5,0,0,0,0,0,0,0,0,1,0
8,16,3.0,0,0,0,0,0,0,0,0,1,0
9,19,5.0,0,0,0,0,0,0,0,0,1,0
10,22,3.0,0,0,0,0,0,0,0,0,1,0
11,23,4.0,0,0,0,0,0,0,0,0,1,0
12,24,4.0,0,0,0,0,0,0,0,0,1,0
13,31,3.0,0,0,0,0,0,0,0,0,1,0
14,34,5.0,0,0,0,0,0,0,0,0,1,0
15,39,5.0,0,0,0,0,0,0,0,0,1,0
16,47,1.0,0,0,0,0,0,0,0,0,1,0
17,53,4.0,0,0,0,0,0,0,0,0,1,0
18,54,4.0,0,0,0,0,0,0,0,0,1,0
19,58,5.0,0,0,0,0,0,0,0,0,1,0

# Apriori Algorithm

In [18]:
from pyECLAT  import ECLAT
eclat_instance = ECLAT(data=df, verbose=True)

  0%|          | 0/4087 [00:00<?, ?it/s]

KeyError: 0

In [ ]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.7)
rules

#####  An leverage value of 0 indicates independence. Range will be [-1 1]
A high conviction value means that the consequent is highly depending on the antecedent and range [0 inf]

In [ ]:
rules.sort_values('lift',ascending = False)[0:20]

In [ ]:
rules[rules.lift>1]